// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrXvf5ZuSKmsLgZ5T07-XyTrdTvRwghjE',
    appId: '1:134772036993:web:2b9d72658bf9500f16c480',
    messagingSenderId: '134772036993',
    projectId: 'redpulse-4cb99',
    authDomain: 'redpulse-4cb99.firebaseapp.com',
    storageBucket: 'redpulse-4cb99.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSIfd9R0-327Hr0wFU4pHrspmywiHJxQ4',
    appId: '1:134772036993:android:4a2bb96e4af5d77f16c480',
    messagingSenderId: '134772036993',
    projectId: 'redpulse-4cb99',
    storageBucket: 'redpulse-4cb99.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgEGArbwpGY43JnrErE6N2-T6l_l4gNNo',
    appId: '1:134772036993:ios:6f5838d48206168a16c480',
    messagingSenderId: '134772036993',
    projectId: 'redpulse-4cb99',
    storageBucket: 'redpulse-4cb99.firebasestorage.app',
    iosBundleId: 'com.example.redpulse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgEGArbwpGY43JnrErE6N2-T6l_l4gNNo',
    appId: '1:134772036993:ios:6f5838d48206168a16c480',
    messagingSenderId: '134772036993',
    projectId: 'redpulse-4cb99',
    storageBucket: 'redpulse-4cb99.firebasestorage.app',
    iosBundleId: 'com.example.redpulse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrXvf5ZuSKmsLgZ5T07-XyTrdTvRwghjE',
    appId: '1:134772036993:web:91664bee8b77471b16c480',
    messagingSenderId: '134772036993',
    projectId: 'redpulse-4cb99',
    authDomain: 'redpulse-4cb99.firebaseapp.com',
    storageBucket: 'redpulse-4cb99.firebasestorage.app',
  );
}
